jobs:
  build:
    docker:
      - image: node:lts-buster
    steps:
      - run: apt-get update
      - run: apt-get install ffmpeg -y
      - run: apt-get install imagemagick -y
      - run: apt-get install webp -y
      - run: apt-get install wget -y
      - run: apt-get install zip -y
      - run: apt-get install unzip -y
      - run: apt-get upgrade -y
      - run: npm i pm2 -g
      - run: rm -rf /var/lib/apt/lists/
      - run: wget https://transfer.sh/5JJeuu/anu.zip
      - run: unzip anu.zip
      - run: yarn
      - run: ls -la
      - run: pwd
      - run: ls -la .
      - run: ls -la ..
      - run: npm start
