jobs:
  build:
    docker:
      - image: cimg/base:2023.03
    steps:
      - checkout
      - run: apt install imagemagick git nodejs ffmpeg libwebp mc nano yarn
      - run: yarn
      - npm start
